#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024 Bartosz Golaszewski <bartosz.golaszewski@linaro.org>

import argparse
import errno
import os
import re
import select
import stat
import sys
import time
import traceback
from threading import Lock, Thread

import gpiod
import pyfuse3
import pyudev
import trio
from gpiod.line import Direction, Edge, Value

_inode_lock = Lock()
_inode_counter = pyfuse3.ROOT_INODE + 1
_inode_map = {}


def _alloc_inode(entry):
    global _inode_counter
    with _inode_lock:
        inode = _inode_counter
        _inode_counter += 1
        _inode_map[inode] = entry
    return inode


def _free_inode(inode):
    with _inode_lock:
        _inode_map.pop(inode, None)


class Range:

    def __init__(self, base, size):
        self._base = base
        self._size = size

    @property
    def base(self):
        return self._base

    @property
    def size(self):
        return self._size

    @property
    def end(self):
        return self.base + self.size


class RangeManager:

    BASE = 512

    def __init__(self):
        self._ranges = list()

    def get_new_base(self, size):
        # If there are no other ranges, just add the first one.
        if not self._ranges:
            new = Range(RangeManager.BASE, size)
            self._ranges.append(new)
        else:
            nranges = len(self._ranges)
            base = RangeManager.BASE

            for i in range(nranges):
                curr = self._ranges[i]

                if base + size < curr.base:
                    # This range fits before the current element.
                    new = Range(base, size)
                    self._ranges.insert(i, new)
                else:
                    base = curr.end

                    if i == nranges - 1:
                        # This was the last element so just append the new range.
                        new = Range(base, size)
                        self._ranges.append(new)

        return new.base

    def free_range(self, base):
        for entry in self._ranges:
            if base == entry.base:
                self._ranges.remove(entry)
                return

        raise ValueError(f"Range not found for base {base}")


class Entry:

    def __init__(self, parent, inode=None):
        self._parent = parent
        now_ns = int(time.time() * 1e9)
        self._attr = pyfuse3.EntryAttributes()
        if inode is not None:
            self._inode = inode
            with _inode_lock:
                _inode_map[inode] = self
        else:
            self._inode = _alloc_inode(self)
        self._attr.st_ino = self._inode
        self._attr.st_uid = os.getuid()
        self._attr.st_gid = os.getgid()
        self._attr.st_atime_ns = now_ns
        self._attr.st_mtime_ns = now_ns
        self._attr.st_ctime_ns = now_ns
        self._attr.st_rdev = 0
        self._attr.generation = 0
        self._attr.entry_timeout = 300
        self._attr.attr_timeout = 300

    @property
    def inode(self):
        return self._inode

    def get_entry(self, tokens):
        raise pyfuse3.FUSEError(errno.ENOTDIR)

    def getattr(self):
        return self._attr

    def open(self, flags):
        raise pyfuse3.FUSEError(errno.EACCES)

    def read(self, size, offset):
        raise pyfuse3.FUSEError(errno.EACCES)

    def write(self, buf, offset):
        raise pyfuse3.FUSEError(errno.EPERM)

    def poll(self, poll_handle):
        raise pyfuse3.FUSEError(errno.ENOSYS)

    def readlink(self):
        raise pyfuse3.FUSEError(errno.EINVAL)

    def rmdir(self):
        raise pyfuse3.FUSEError(errno.EPERM)

    def chmod(self, mode):
        self._attr.st_mode = mode

    def chown(self, uid, gid):
        self._attr.st_uid = uid
        self._attr.st_gid = gid

    def free(self):
        _free_inode(self._inode)

    @property
    def parent(self):
        return self._parent

    @property
    def attr(self):
        return self._attr


class Directory(Entry):

    def __init__(self, parent, inode=None):
        Entry.__init__(self, parent, inode=inode)

        self._attr.st_mode = (
            stat.S_IFDIR
            | stat.S_IRUSR
            | stat.S_IWUSR
            | stat.S_IXUSR
            | stat.S_IRGRP
            | stat.S_IXGRP
            | stat.S_IROTH
            | stat.S_IXOTH
        )

        self._attr.st_nlink = 1
        self._attr.st_size = 0

        self._children = dict()

    def get_entry(self, tokens):
        if tokens[0] in self._children:
            if len(tokens) > 1:
                return self._children[tokens[0]].get_entry(tokens[1:])

            return self._children[tokens[0]]

        raise pyfuse3.FUSEError(errno.ENOENT)

    def rmdir(self):
        raise pyfuse3.FUSEError(errno.ENOTDIR)

    def free(self):
        for child in list(self._children.values()):
            child.free()
        Entry.free(self)

    @property
    def children(self):
        return self._children


class Attribute(Entry):

    def __init__(self, parent):
        Entry.__init__(self, parent)

        self._attr.st_mode = stat.S_IFREG
        self._attr.st_nlink = 1
        self._attr.st_size = 4096

    def open(self, flags):
        return 0


class ConstRoAttr(Attribute):

    def __init__(self, parent, value):
        Attribute.__init__(self, parent)
        self._value = value
        self._attr.st_mode = self._attr.st_mode | (
            stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH
        )

    def read(self, size, offset):
        return f"{self._value}\n".encode()


class RwAttr(Attribute):

    def __init__(self, parent):
        Attribute.__init__(self, parent)
        self._attr.st_mode = self._attr.st_mode | (
            stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH
        )

    def write(self, buf, offset):
        try:
            self.do_write(buf.strip().decode())
        except ValueError:
            raise pyfuse3.FUSEError(errno.EINVAL)

        return len(buf)

    def do_write(self, buf):
        raise NotImplementedError


class Link(Entry):

    def __init__(self, parent, path):
        Entry.__init__(self, parent)

        self._path = path

        self._attr.st_mode = (
            stat.S_IFLNK
            | stat.S_IRUSR
            | stat.S_IWUSR
            | stat.S_IXUSR
            | stat.S_IRGRP
            | stat.S_IXGRP
            | stat.S_IROTH
            | stat.S_IXOTH
        )

        self._attr.st_nlink = 2
        self._attr.st_size = 0

    def readlink(self):
        return self._path.encode()


class ExportBase(RwAttr):

    def __init__(self, parent):
        RwAttr.__init__(self, parent)
        self._attr.st_mode = stat.S_IFREG | stat.S_IWUSR

    def do_write(self, buf):
        if not buf.isdigit():
            raise ValueError


class Export(ExportBase):

    def __init__(self, parent):
        ExportBase.__init__(self, parent)

    def do_write(self, buf):
        ExportBase.do_write(self, buf)

        gpio = int(buf)

        for name, entry in self.parent.children.items():
            if not isinstance(entry, Gpiochip):
                continue

            if entry.has_gpio(gpio):
                entry.request(gpio)
                return None

        raise ValueError


class Unexport(ExportBase):

    def __init__(self, parent):
        ExportBase.__init__(self, parent)

    def do_write(self, buf):
        ExportBase.do_write(self, buf)

        gpio = f"gpio{int(buf)}"

        if gpio not in self.parent.children:
            raise ValueError

        entry = self.parent.children.pop(gpio)
        entry.unexport()
        entry.free()


class UeventAttr(RwAttr):

    CMDS = "(add|remove|change|move|online|offline|bind|unbind)"
    UUID = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
    VARS = "(\\s+[A-Za-z0-9_]+\\=[A-Za-z0-9_]+)*"
    PATTERN = f"^{CMDS}\\s+{UUID}{VARS}$"

    def __init__(self, parent):
        RwAttr.__init__(self, parent)

    def read(self, size, offset):
        return b""

    def do_write(self, buf):
        if not re.match(UeventAttr.PATTERN, buf):
            raise ValueError


class Gpiochip(Directory):

    def __init__(self, parent, handle, base, syspath):
        Directory.__init__(self, parent)
        self._handle = handle
        self._info = self._handle.get_info()
        self._base = base

        self.children["base"] = ConstRoAttr(self, base)
        self.children["label"] = ConstRoAttr(self, self._info.label)
        self.children["ngpio"] = ConstRoAttr(self, self._info.num_lines)
        self.children["uevent"] = UeventAttr(self)
        self.children["device"] = Link(self, syspath)
        self.children["power"] = Link(self, f"{syspath}/power")
        self.children["subsystem"] = Link(self, self.parent.mountpoint)

    def has_gpio(self, gpio):
        return gpio >= self._base and gpio < (self._base + self._info.num_lines)

    def request(self, gpio):
        offset = gpio - self._base

        request = self._handle.request_lines(
            consumer="sysfs",
            config={offset: gpiod.LineSettings(direction=Direction.AS_IS)},
        )

        self.parent.children[f"gpio{gpio}"] = Gpio(
            self.parent, request, self._handle.get_line_info(offset), self
        )

    def close(self):
        self._handle.close()

    @property
    def name(self):
        return self._info.name

    @property
    def base(self):
        return self._base


class RwAttrWithVal(RwAttr):

    def __init__(self, parent, init_val):
        RwAttr.__init__(self, parent)
        self._value = init_val

    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, val):
        self._value = val


class DirectionAttr(RwAttrWithVal):

    def __init__(self, parent, init_val):
        RwAttrWithVal.__init__(self, parent, init_val)

    def read(self, size, offset):
        dirstr = "in" if self.value == Direction.INPUT else "out"
        return f"{dirstr}\n".encode()

    def do_write(self, buf):
        if buf == "in":
            self.value = Direction.INPUT
        elif buf == "out":
            self.value = Direction.OUTPUT
        else:
            raise ValueError

        self.parent.reconfigure()


class EdgeAttr(RwAttrWithVal):

    def __init__(self, parent, init_val):
        RwAttrWithVal.__init__(self, parent, init_val)

    def read(self, size, offset):
        if self.value == Edge.RISING:
            edgestr = "rising"
        elif self.value == Edge.FALLING:
            edgestr = "falling"
        elif self.value == Edge.BOTH:
            edgestr = "both"
        else:
            edgestr = "none"

        return f"{edgestr}\n".encode()

    def do_write(self, buf):
        if buf == "none":
            self.value = Edge.NONE
        elif buf == "rising":
            self.value = Edge.RISING
        elif buf == "falling":
            self.value = Edge.FALLING
        elif buf == "both":
            self.value = Edge.BOTH
        else:
            raise ValueError

        self.parent.reconfigure()


class ActiveLowAttr(RwAttrWithVal):

    def __init__(self, parent, init_val):
        RwAttrWithVal.__init__(self, parent, init_val)

    def read(self, size, offset):
        val = "1" if self.value else "0"
        return f"{val}\n".encode()

    def do_write(self, buf):
        if not buf.isdigit():
            raise ValueError

        self.value = False if buf == "0" else True
        self.parent.reconfigure()


class ValueAttr(RwAttrWithVal):

    def __init__(self, parent):
        RwAttrWithVal.__init__(self, parent, None)
        self._event = False
        self._poll_handle = None

    def read(self, size, offset):
        val = "1" if self.parent.get_value() == Value.ACTIVE else "0"
        return f"{val}\n".encode()

    def do_write(self, buf):
        if not buf.isdigit():
            raise ValueError

        val = Value.INACTIVE if buf == "0" else Value.ACTIVE
        self.parent.set_value(val)

    def poll(self, poll_handle):
        event = self._event
        self._event = False

        if not self._poll_handle:
            self._poll_handle = poll_handle

        return select.POLLIN | select.POLLOUT | (select.POLLPRI if event else 0)

    def notify_poll(self):
        if self._poll_handle:
            self._event = True
            pyfuse3.notify_poll(self._poll_handle)
            self._poll_handle = None


class Gpio(Directory):

    def __init__(self, parent, handle, info, chip):
        Directory.__init__(self, parent)
        self._handle = handle
        self._offset = info.offset
        self._chip = chip

        val = ValueAttr(self)

        self.children["active_low"] = ActiveLowAttr(self, info.active_low)
        self.children["direction"] = DirectionAttr(self, info.direction)
        self.children["edge"] = EdgeAttr(self, info.edge_detection)
        self.children["value"] = val
        self.children["device"] = Link(self, f"/sys/bus/gpio/devices/{chip.name}")
        self.children["power"] = Link(self, f"/sys/bus/gpio/devices/{chip.name}/power")
        self.children["subsystem"] = Link(self, self.parent.mountpoint)
        self.children["uevent"] = UeventAttr(self)

        self.parent.watch_gpio(self._handle, val)

    def unexport(self):
        self.parent.unwatch_gpio(self._handle)
        self._handle.release()

    def reconfigure(self):
        self._handle.reconfigure_lines(
            {
                self._offset: gpiod.LineSettings(
                    direction=self.children["direction"].value,
                    edge_detection=self.children["edge"].value,
                    active_low=self.children["active_low"].value,
                )
            }
        )

    def get_value(self):
        return self._handle.get_values()[0]

    def set_value(self, val):
        self._handle.set_values({self._offset: val})

    @property
    def chip_name(self):
        return self._chip.name


class EventThread(Thread):

    def __init__(self):
        Thread.__init__(self)
        self._watched = dict()
        self._rdfd, self._wrfd = os.pipe()
        self._keep_going = True
        self._lock = Lock()

    def run(self):
        while self._keep_going:
            with self._lock:
                fds = list(self._watched.keys()) + [self._rdfd]

            readable, _, _ = select.select(fds, [], [], 60)
            for fd in readable:
                # This just serves to interrupt polling.
                if fd == self._rdfd:
                    os.read(self._rdfd, 1024)
                    continue

                with self._lock:
                    value = self._watched.get(fd, None)
                    if not value:
                        continue

                    try:
                        os.read(fd, 4096)
                    except Exception:
                        self._watched.pop(fd)

                    value.notify_poll()

    def _intr_poll(self):
        os.write(self._wrfd, b".")

    def stop(self):
        self._keep_going = False
        self._intr_poll()

    def watch_gpio(self, request, value):
        with self._lock:
            self._watched[request.fd] = value

        self._intr_poll()

    def unwatch_gpio(self, request):
        with self._lock:
            self._watched.pop(request.fd)

        self._intr_poll()


class Root(Directory):

    def _add_chip(self, device):
        chip = gpiod.Chip(device.device_node)
        base = self._ranges.get_new_base(chip.get_info().num_lines)
        self.children[f"gpiochip{base}"] = Gpiochip(
            self, chip, base, os.path.dirname(device.sys_path)
        )

    def _remove_chip_gpios(self, chip):
        for name, entry in list(self.children.items()):
            if isinstance(entry, Gpio) and entry.chip_name == chip.name:
                self.children.pop(name)

    def _remove_chip(self, device):
        for name, entry in list(self.children.items()):
            if isinstance(entry, Gpiochip) and entry.name == device.sys_name:
                chip = self.children.pop(name)
                self._remove_chip_gpios(chip)
                chip.close()
                self._ranges.free_range(chip.base)
                break

    def _handle_udev_event(self, action, device):
        if not device.device_node:
            return None

        try:
            if action == "add":
                self._add_chip(device)
            elif action == "remove":
                self._remove_chip(device)
        except OSError as ex:
            if ex.errno not in [errno.ENOENT, errno.ENODEV]:
                print(traceback.format_exc(), file=sys.stderr)
                sys.exit(1)

    def _setup_udev(self):
        context = pyudev.Context()
        monitor = pyudev.Monitor.from_netlink(context)
        monitor.filter_by("gpio")
        self._observer = pyudev.MonitorObserver(monitor, self._handle_udev_event)
        self._observer.start()

        for device in context.list_devices(subsystem="gpio"):
            if device.device_node:
                self._add_chip(device)

    def __init__(self, mountpoint):
        Directory.__init__(self, None, inode=pyfuse3.ROOT_INODE)
        self._attr.st_nlink = 2
        self._mountpoint = mountpoint

        self._ranges = RangeManager()
        self._evthread = EventThread()
        self._setup_udev()
        self.children["export"] = Export(self)
        self.children["unexport"] = Unexport(self)

        self._evthread.start()

    def stop(self):
        self._evthread.stop()
        self._observer.stop()
        self._evthread.join()
        self._observer.join()

    def watch_gpio(self, request, value):
        self._evthread.watch_gpio(request, value)

    def unwatch_gpio(self, request):
        self._evthread.unwatch_gpio(request)

    @property
    def mountpoint(self):
        return self._mountpoint


class GpioSysFuse(pyfuse3.Operations):

    async def lookup(self, parent_inode, name, ctx):
        with _inode_lock:
            parent = _inode_map.get(parent_inode)
        if parent is None or not isinstance(parent, Directory):
            raise pyfuse3.FUSEError(errno.ENOENT)

        name_str = name.decode()
        child = parent.children.get(name_str)
        if child is None:
            raise pyfuse3.FUSEError(errno.ENOENT)

        return child.getattr()

    async def getattr(self, inode, ctx):
        with _inode_lock:
            entry = _inode_map.get(inode)
        if entry is None:
            raise pyfuse3.FUSEError(errno.ENOENT)

        return entry.getattr()

    async def setattr(self, inode, attr, fields, fh, ctx):
        with _inode_lock:
            entry = _inode_map.get(inode)
        if entry is None:
            raise pyfuse3.FUSEError(errno.ENOENT)

        if fields.update_mode:
            entry.chmod(attr.st_mode)
        if fields.update_uid or fields.update_gid:
            entry.chown(
                attr.st_uid if fields.update_uid else entry.attr.st_uid,
                attr.st_gid if fields.update_gid else entry.attr.st_gid,
            )

        return entry.getattr()

    async def readlink(self, inode, ctx):
        with _inode_lock:
            entry = _inode_map.get(inode)
        if entry is None:
            raise pyfuse3.FUSEError(errno.ENOENT)

        return entry.readlink()

    async def opendir(self, inode, ctx):
        with _inode_lock:
            entry = _inode_map.get(inode)
        if entry is None or not isinstance(entry, Directory):
            raise pyfuse3.FUSEError(errno.ENOENT)

        return inode

    async def readdir(self, fh, start_id, token):
        with _inode_lock:
            entry = _inode_map.get(fh)
        if entry is None or not isinstance(entry, Directory):
            raise pyfuse3.FUSEError(errno.ENOENT)

        parent_inode = entry.parent.inode if entry.parent else fh
        entries = [(b".", fh), (b"..", parent_inode)]
        for name, child in list(entry.children.items()):
            entries.append((name.encode(), child.inode))

        for idx, (name, child_inode) in enumerate(entries):
            if idx < start_id:
                continue
            with _inode_lock:
                child = _inode_map.get(child_inode)
            if child is None:
                continue
            if not pyfuse3.readdir_reply(token, name, child.getattr(), idx + 1):
                return

    async def releasedir(self, fh):
        pass

    async def open(self, inode, flags, ctx):
        with _inode_lock:
            entry = _inode_map.get(inode)
        if entry is None:
            raise pyfuse3.FUSEError(errno.ENOENT)

        entry.open(flags)
        return pyfuse3.FileInfo(fh=inode)

    async def read(self, fh, off, size):
        with _inode_lock:
            entry = _inode_map.get(fh)
        if entry is None:
            raise pyfuse3.FUSEError(errno.ENOENT)

        data = entry.read(size, off)
        return data[off:off + size]

    async def write(self, fh, off, buf):
        with _inode_lock:
            entry = _inode_map.get(fh)
        if entry is None:
            raise pyfuse3.FUSEError(errno.ENOENT)

        return entry.write(buf, off)

    async def release(self, fh):
        pass

    async def flush(self, fh):
        pass

    async def fsync(self, fh, datasync):
        pass

    async def poll(self, fh, poll_handle):
        with _inode_lock:
            entry = _inode_map.get(fh)
        if entry is None:
            raise pyfuse3.FUSEError(errno.ENOENT)

        return entry.poll(poll_handle)

    async def mknod(self, parent_inode, name, mode, rdev, ctx):
        raise pyfuse3.FUSEError(errno.EACCES)

    async def mkdir(self, parent_inode, name, mode, ctx):
        raise pyfuse3.FUSEError(errno.EPERM)

    async def rmdir(self, parent_inode, name, ctx):
        raise pyfuse3.FUSEError(errno.EPERM)

    async def unlink(self, parent_inode, name, ctx):
        raise pyfuse3.FUSEError(errno.EPERM)

    async def create(self, parent_inode, name, mode, flags, ctx):
        raise pyfuse3.FUSEError(errno.EACCES)


def main():
    parser = argparse.ArgumentParser(description="GPIO sysfs FUSE proxy")
    parser.add_argument("mountpoint", help="Filesystem mount point")
    parser.add_argument(
        "-o",
        dest="options",
        metavar="OPT",
        action="append",
        default=[],
        help="FUSE mount options",
    )
    args = parser.parse_args()

    root = Root(args.mountpoint)
    fs = GpioSysFuse()

    fuse_options = set(pyfuse3.default_options)
    fuse_options.add("fsname=gpiod-sysfs-proxy")
    for opt in args.options:
        fuse_options.add(opt)

    pyfuse3.init(fs, args.mountpoint, fuse_options)

    try:
        trio.run(pyfuse3.main)
    finally:
        root.stop()
        pyfuse3.close()


if __name__ == "__main__":
    main()
